[package]
name = "rsw-lib"
version = "0.1.0"
authors = ["suren <suren-m>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.1"
chrono = "0.4"
serde = "1.0.118"
log = "0.4.11"